<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7AKMRUB" failures="1" tests="2" name="P360_UI_USER_MODULE" time="100.459" errors="0" timestamp="2023-09-19T00:05:40 IST">
  <testcase classname="com.p360.Main.testCases.TC_Main_Users" name="test_Main_ViewAgreedConditions" time="34.781"/>
  <testcase classname="com.p360.Main.testCases.TC_Main_Users" name="test_Main_ChangeEmail" time="39.255">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	To check email change or not expected [User with given email already exists.] but found [Email is updated successfully.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
To check email change or not expected [User with given email already exists.] but found [Email is updated successfully.]
at com.p360.Main.pageObject.PO_Main_UsersPage.changeEmail(PO_Main_UsersPage.java:473)
at com.p360.Main.testCases.TC_Main_Users.test_Main_ChangeEmail(TC_Main_Users.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_Main_ChangeEmail -->
</testsuite> <!-- P360_UI_USER_MODULE -->
